# Generated by Django 5.0 on 2024-07-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/my_pic_MAPGgqs.jpg",
                null=True,
                upload_to="avatars",
            ),
        ),
    ]
