# Generated by Django 5.0 on 2024-07-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/dummy_pic.png",
                null=True,
                upload_to="avatars",
            ),
        ),
    ]
