# Generated by Django 5.0 on 2024-07-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gain",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="wallet",
            field=models.FloatField(default=0),
        ),
    ]
