# Generated by Django 5.0 on 2024-03-18 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_friendshiprequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FriendshipRequest",
        ),
    ]
