# Generated by Django 5.0 on 2024-03-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_post_likes_count_comment_like_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="attachments",
        ),
    ]
