# Generated by Django 5.0 on 2024-03-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_post_reports_count_report_post_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments",
            field=models.ManyToManyField(blank=True, to="post.comment"),
        ),
        migrations.AddField(
            model_name="post",
            name="comments_count",
            field=models.IntegerField(default=0),
        ),
    ]
