# Generated by Django 5.0 on 2024-07-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversationmessage",
            old_name="created_by",
            new_name="sender",
        ),
    ]
