# Generated by Django 5.0 on 2024-07-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_rename_created_by_conversationmessage_sender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversationmessage",
            old_name="body",
            new_name="message",
        ),
    ]
